name: GitHub Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'chore: release v')"
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - name: Get version and changelog
        id: get-version
        run: |
          echo "tag=v$(node -p "require('./package.json').version")" >> "$GITHUB_OUTPUT"
          awk '/^## /{c++} c==1' CHANGELOG.md > .changelog.md

      - name: GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ steps.get-version.outputs.tag }}" --notes-file .changelog.md
